# Generated by Django 5.0.1 on 2024-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_redirects_date_alter_redirects_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirects',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='redirects',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
