# Generated by Django 5.0.1 on 2024-05-24 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_redirects_date_alter_redirects_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirects',
            options={'ordering': ['-date'], 'verbose_name': 'Redirect', 'verbose_name_plural': 'Redirects'},
        ),
        migrations.AlterField(
            model_name='redirects',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to=settings.AUTH_USER_MODEL),
        ),
    ]
